title: TimZaman.com
description: Tim Zaman's personal website

theme: just-the-docs

url: "https://timzaman.com"
baseurl: ""

permalink: pretty

favicon_ico: "/favicon.ico"

search_enabled: false
ga_tracking: G-CK6YBRC7X6

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - vendor/
  - node_modules/

sass:
  quiet_deps: true
  silence_deprecations:
    - import
    - global-builtin
    - color-functions
